# Generated by Django 2.2.16 on 2021-01-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_alter_is_archived_field_on_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='filter_on_dashboard',
            field=models.BooleanField(default=True, help_text='Make available to filter on dashboard'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Archived terms can be viewed but not set on content.', verbose_name='Archived'),
        ),
        migrations.AddField(
            model_name='option',
            name='filter_on_dashboard',
            field=models.BooleanField(default=True, help_text='Make available to filter on dashboard'),
        ),
        migrations.AddField(
            model_name='option',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Archived terms can be viewed but not set on content.', verbose_name='Archived'),
        ),
    ]
